### ISSUE TITLE
port to heatseeker?

### ISSUE THREAD

**Issue by fdncred** [phiresky/nushell-history-skim#1]
Hey @phiresky,
I'd love to see something like this in nushell. Unfortunately, skim is a non-starter since it doesn't support Windows. I was wondering if you'd be interested & willing to port this to something like [heatseeker](https://github.com/rschmitt/heatseeker) or another cross platform fuzzy finder?

**Comment by phiresky** [comment]
I looked into heatseeker and I think one other fuzzy-finder rust thing, but afaik neither of them had a Rust API that was powerful enough to enable something like this..

**Comment by fdncred** [comment]
darn. I so wish skim would adopt crossterm. I saw there are blocking issues that have gone unresolved for a long time in the skim and crossterm repo. I'd just like to find some alternate solution.
